name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Build and Test
      run: sbt -v +test
  pgp_debug:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - run: gpg --version && echo $PGP_SECRET | base64 -w0 -d | gpg --import && gpg --list-sigs && gpg --list-keys && echo pizza > /tmp/pizza.txt && gpg --local-user 08109B5E42E0C41D --batch --pinentry-mode loopback --passphrase $PGP_PASSPHRASE --detach-sign --armor --use-agent --output /tmp/pizza.txt.asc /tmp/pizza.txt
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
