name: Linter
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Scalafmt Check
      run: sbt scalafmtCheck
    - name: Scalafix Check
      run: "sbt 'scalafixAll --check'"
